
eureka:
  instance:
    hostname: localhost
server:
  port: '9002'
spring:
  application:
    name: tiffin-module
  datasource:
    password: admin
    url: jdbc:postgresql://localhost:5432/tiffinbookingdb?createDatabaseIfNotExist=true
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
